version: "3.9"
volumes:
  php-fpm-socket:
  psysh-store:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - target: 80
        published: 8075
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend

  # db:
  #   build:
  #     context: .
  #     dockerfile: ./infra/docker/mysql/Dockerfile
  #   ports:
  #     - target: 3306
  #       published: 8076
  #       protocol: tcp
  #       mode: host
  #   volumes:
  #     - type: bind
  #       source: ./var/mysql
  #       target: /var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=mydatabase
  #     - MYSQL_USER=myuser
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_ROOT_PASSWORD=secret
